[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tmdbapis"
version = "0.1.0"
description = "TMDb API Wrapper"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests>=2.28.0",
]

[tool.setuptools.packages.find]
where = ["."]
